// Code generated by "stringer -type Code -linecomment -output status_string.go"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[Input-10]
	_ = x[InputSensitive-11]
	_ = x[Success-20]
	_ = x[Redirect-30]
	_ = x[RedirectPermanent-31]
	_ = x[TemporaryFailure-40]
	_ = x[ServerUnavailable-41]
	_ = x[CGIError-42]
	_ = x[ProxyError-43]
	_ = x[SlowDown-44]
	_ = x[PermanentFailure-50]
	_ = x[NotFound-51]
	_ = x[Gone-52]
	_ = x[ProxyRequestRefused-53]
	_ = x[BadRequest-59]
	_ = x[ClientCertificateRequired-60]
	_ = x[CertificateNotAuthorized-61]
	_ = x[ClientCertificateNotValid-62]
}

const (
	_Code_name_0 = "<UNDEFINED STATUS CODE>"
	_Code_name_1 = "INPUTSENSITIVE INPUT"
	_Code_name_2 = "SUCCESS"
	_Code_name_3 = "REDIRECT - TEMPORARREDIRECT - PERMANENT"
	_Code_name_4 = "TEMPORARY FAILURESERVER UNAVAILABLECGI ERRORPROXY ERRORSLOW DOWN"
	_Code_name_5 = "PERMANENT FAILURENOT FOUNDGONEPROXY REQUEST REFUSED"
	_Code_name_6 = "BAD REQUESTCLIENT CERTIFICATE REQUIREDCERTIFICATE NOT AUTHORIZEDCERTIFICATE NOT VALID"
)

var (
	_Code_index_1 = [...]uint8{0, 5, 20}
	_Code_index_3 = [...]uint8{0, 19, 39}
	_Code_index_4 = [...]uint8{0, 17, 35, 44, 55, 64}
	_Code_index_5 = [...]uint8{0, 17, 26, 30, 51}
	_Code_index_6 = [...]uint8{0, 11, 38, 64, 85}
)

func (i Code) String() string {
	switch {
	case i == 0:
		return _Code_name_0
	case 10 <= i && i <= 11:
		i -= 10
		return _Code_name_1[_Code_index_1[i]:_Code_index_1[i+1]]
	case i == 20:
		return _Code_name_2
	case 30 <= i && i <= 31:
		i -= 30
		return _Code_name_3[_Code_index_3[i]:_Code_index_3[i+1]]
	case 40 <= i && i <= 44:
		i -= 40
		return _Code_name_4[_Code_index_4[i]:_Code_index_4[i+1]]
	case 50 <= i && i <= 53:
		i -= 50
		return _Code_name_5[_Code_index_5[i]:_Code_index_5[i+1]]
	case 59 <= i && i <= 62:
		i -= 59
		return _Code_name_6[_Code_index_6[i]:_Code_index_6[i+1]]
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
